version: 2.1

orbs:
  windows: circleci/windows@5

jobs:
  test:
    executor:
      name: windows/default
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Install reportgenerator"
          command: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.1
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Build Application"
          command: dotnet.exe build 
      - run: 
          name: show
          command: tree /f
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage -p:CollectCoverage=true -p:CoverletOutput="coverage" -p:CoverletOutputFormat="json%2cCobertura" -p:MergeWith="AspNetCoreTests.UnitTests\coverage.json"
      - run: 
          name: test
          command: |
            tree /f
            cp .\AspNetCoreTests.UnitTests\coverage.cobertura.xml .\coverage\coverage.cobertura.xml
            dir .\coverage
      - store_artifacts:
          path: coverage
          destination: coverage
      - run: 
          name: "Generating code coverage reports"
          command: dotnet.exe reportgenerator -reports:~\project\coverage\coverage.cobertura.xml 
                 -targetdir:~\project\coverage -reporttypes:"HTML;HTMLSummary"
      
      # - run: 
      #     name: show html
      #     command: tree /f
      # - store_artifacts:
      #     path: coverage

  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: echo "Build"
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test