version: 2.1

orbs:
  windows: circleci/windows@5

jobs:
  test:
    executor:
      name: windows/default
    working_directory: ~\project
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Build Application"
          command: dotnet.exe build 
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage -p:CollectCoverage=true -p:CoverletOutput="coverage" -p:CoverletOutputFormat="json%2cCobertura" -p:MergeWith="AspNetCoreTests.UnitTests\coverage.json"
      - run: 
          name: Generate reports
          command: |
            tree /f
            cp AspNetCoreTests.UnitTests\coverage.cobertura.xml coverage\coverage.cobertura.xml
            dotnet tool install --tool-path tools dotnet-reportgenerator-globaltool --version 4.6.1
            ./tools/reportgenerator -reports:"coverage\coverage.cobertura.xml" -targetdir:"coverage" -reporttypes:"HTML;HTMLSummary"
      # - persist_to_workspace:
      #     # Must be an absolute path, or relative path from working_directory
      #     root: coverage
      #     # Must be relative path from root
      #     paths:
      #       - coverage
      - store_artifacts:
          path: coverage
          destination: coverage
      
      - run: 
          name: show html
          command: tree /f
      - store_test_results: 
          path: coverage

  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: echo "Build"
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test