version: 2.1
jobs:
  buildev:
    docker:
      - image: cimg/base:2023.05
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
     # test
      - run: |
          export DOCKER_BUILDKIT=0
          export COMPOSE_DOCKER_CLI_BUILD=0
          docker-compose -f docker-compose-integration.yml up -d

workflows:
  my_workflow:
    jobs:
      - buildev
      