version: 2.1

orbs:
  windows: circleci/windows@5

jobs:
  test:
    executor:
      name: windows/default
    steps:
      - checkout
      - run: 
          name: Install reportgenerator
          command: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.1
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore AspNetCoreTests.sln
      - run:
          name: "Build Application"
          command: dotnet.exe build 
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test --no-build --verbosity normal --logger trx -r coverage -p:CollectCoverage=true 
               -p:CoverletOutput="coverage" 
               -p:CoverletOutputFormat="json%2cCobertura" 
               -p:MergeWith="coverage\coverage.json" 
      - run: 
          name: test
          command: tree /f

  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --no-restore
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test