version: 2.1
orbs:
  docker-compose: parrable/docker-compose@1.0.1
jobs:
  check-and-build-only:
    executor: docker/docker
    steps:
      - checkout
      - run:
          name: "Docker compose build"
          command: docker-compose build
workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only