# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:2.1 AS build
WORKDIR /src
COPY *.csproj ./
RUN dotnet restore
# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Serve Stage
FROM mcr.microsoft.com/dotnet/aspnet:2.1
WORKDIR /src
COPY --from=build /src/out .


ENTRYPOINT [ "dotnet", "DotNetCoreSampleApi.dll" ]
